spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/university
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: spring-security-app
#  data:
#    jdbc:
#      dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9191


#spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
#spring.datasource.hikari.allow-pool-suspension=true