name: Java CI with Maven build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env: # Or as an environment variable
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: university
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE_NAME: university
          DATABASE_USERNAME: ${{ secrets.DB_USERNAME }}
          DATABASE_ENDPOINT: 127.0.0.1
        ports:
          - 3306:3306
          # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        check-latest: true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
